/**
 * rebuttal.ts — Phase 2.2
 *
 * POST /api/rebuttal
 * Accepts an analysis payload (from Phase 2.1 pipeline or manual call).
 * Returns 3 ranked, framework-based rebuttals generated by Claude.
 * Persists every generated rebuttal set to PostgreSQL via Prisma.
 */

import type { FastifyInstance } from "fastify";
import {
  generateRebuttals,
  type AnalysisPayload,
} from "../services/responseGenerator.js";

export async function rebuttalRoutes(fastify: FastifyInstance) {
  fastify.post<{ Body: AnalysisPayload }>(
    "/api/rebuttal",
    async (request, reply) => {
      const body = request.body;

      if (!body?.raw_input || typeof body.raw_input !== "string") {
        return reply.status(400).send({
          error: "Invalid request",
          message: "raw_input must be a non-empty string",
        });
      }

      // Normalise category — fall back to "other"
      const payload: AnalysisPayload = {
        raw_input: body.raw_input.trim(),
        category: body.category ?? "other",
        intent: body.intent,
        emotional_tone: body.emotional_tone,
        urgency: body.urgency,
        confidence: body.confidence,
        signals: body.signals,
      };

      // Generate rebuttals via Claude
      const output = await generateRebuttals(payload);

      // Persist to PostgreSQL
      try {
        const [r1, r2, r3] = output.rebuttals;
        await fastify.prisma.rebuttal.create({
          data: {
            raw_input: payload.raw_input,
            category: payload.category,
            intent: payload.intent ?? null,
            emotional_tone: payload.emotional_tone ?? null,
            urgency: payload.urgency ?? null,
            rebuttal_1: r1?.text ?? "",
            rebuttal_2: r2?.text ?? "",
            rebuttal_3: r3?.text ?? "",
            rebuttals_json: output as unknown as object,
            confidence: payload.confidence ?? null,
          },
        });
      } catch (dbErr) {
        // Log but don't fail the request — user gets rebuttals regardless
        fastify.log.error({ err: dbErr }, "Failed to persist rebuttal to DB");
      }

      return reply.send(output);
    }
  );
}
